"exports.$1 = (req, res, next) => {"
"    if (req.method === 'POST') {"
"        let add$2 = () => {"
"            Tranzakt.create({"
"                createdAt: $4.default"
"            }).then(rezzzzie => {"
"                console.log('success')"
"                res.json({"
"                    transaction: 'sucessxs'"
"                })"
"            }).catch(err => {"
"                res.json({"
"                    no: 'good',"
"                    err: err.stack,"
"                    sean: 'sean322'"
"                })"
"                return console.error(err.stack)"
"            })"
"        }"
"        try {"
"            add$2()"
"        } catch {"
"            console.error(err.stack), console.log(`\\nERRORSTACK>\\n\\n<ERRORSTACK\\n`)"
"        }"
"    } else if (req.method === 'GET') {"
"        let get$3 = () => {"
"            $4.find({}, (err, result) => {"
"                if (!err) {"
"                    res.json({"
"                        result"
"                    })"
"                }"
"            }).catch(err => {"
"                res.json({"
"                    no: 'good',"
"                    err: err.stack,"
"                    sean: 'sean322'"
"                })"
"                return console.error(err.stack)"
"            })"
"        }"
"        get$3()"
"    }"
"}"